/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as SetupsRouteImport } from './routes/setups'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedMyBookingsRouteImport } from './routes/_authenticated/my-bookings'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminTournamentsRouteImport } from './routes/_authenticated/admin.tournaments'
import { Route as AuthenticatedAdminSessionsRouteImport } from './routes/_authenticated/admin.sessions'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminPcsRouteImport } from './routes/_authenticated/admin.pcs'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin.bookings'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupsRoute = SetupsRouteImport.update({
  id: '/setups',
  path: '/setups',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMyBookingsRoute = AuthenticatedMyBookingsRouteImport.update({
  id: '/my-bookings',
  path: '/my-bookings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTournamentsRoute =
  AuthenticatedAdminTournamentsRouteImport.update({
    id: '/tournaments',
    path: '/tournaments',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSessionsRoute =
  AuthenticatedAdminSessionsRouteImport.update({
    id: '/sessions',
    path: '/sessions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPcsRoute = AuthenticatedAdminPcsRouteImport.update({
  id: '/pcs',
  path: '/pcs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/setups': typeof SetupsRoute
  '/tournaments': typeof TournamentsRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/pcs': typeof AuthenticatedAdminPcsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/setups': typeof SetupsRoute
  '/tournaments': typeof TournamentsRoute
  '/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/admin/pcs': typeof AuthenticatedAdminPcsRoute
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/booking': typeof BookingRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/setups': typeof SetupsRoute
  '/tournaments': typeof TournamentsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/my-bookings': typeof AuthenticatedMyBookingsRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRoute
  '/_authenticated/admin/pcs': typeof AuthenticatedAdminPcsRoute
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/sessions': typeof AuthenticatedAdminSessionsRoute
  '/_authenticated/admin/tournaments': typeof AuthenticatedAdminTournamentsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/pricing'
    | '/setups'
    | '/tournaments'
    | '/admin'
    | '/my-bookings'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/pcs'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/tournaments'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/pricing'
    | '/setups'
    | '/tournaments'
    | '/my-bookings'
    | '/admin/bookings'
    | '/admin/customers'
    | '/admin/pcs'
    | '/admin/reports'
    | '/admin/sessions'
    | '/admin/tournaments'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/booking'
    | '/contact'
    | '/pricing'
    | '/setups'
    | '/tournaments'
    | '/_authenticated/admin'
    | '/_authenticated/my-bookings'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/pcs'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/sessions'
    | '/_authenticated/admin/tournaments'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  BookingRoute: typeof BookingRoute
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  SetupsRoute: typeof SetupsRoute
  TournamentsRoute: typeof TournamentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setups': {
      id: '/setups'
      path: '/setups'
      fullPath: '/setups'
      preLoaderRoute: typeof SetupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/my-bookings': {
      id: '/_authenticated/my-bookings'
      path: '/my-bookings'
      fullPath: '/my-bookings'
      preLoaderRoute: typeof AuthenticatedMyBookingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tournaments': {
      id: '/_authenticated/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AuthenticatedAdminTournamentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sessions': {
      id: '/_authenticated/admin/sessions'
      path: '/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AuthenticatedAdminSessionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/pcs': {
      id: '/_authenticated/admin/pcs'
      path: '/pcs'
      fullPath: '/admin/pcs'
      preLoaderRoute: typeof AuthenticatedAdminPcsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRoute
  AuthenticatedAdminPcsRoute: typeof AuthenticatedAdminPcsRoute
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSessionsRoute: typeof AuthenticatedAdminSessionsRoute
  AuthenticatedAdminTournamentsRoute: typeof AuthenticatedAdminTournamentsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminCustomersRoute: AuthenticatedAdminCustomersRoute,
  AuthenticatedAdminPcsRoute: AuthenticatedAdminPcsRoute,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSessionsRoute: AuthenticatedAdminSessionsRoute,
  AuthenticatedAdminTournamentsRoute: AuthenticatedAdminTournamentsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedMyBookingsRoute: typeof AuthenticatedMyBookingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedMyBookingsRoute: AuthenticatedMyBookingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  BookingRoute: BookingRoute,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  SetupsRoute: SetupsRoute,
  TournamentsRoute: TournamentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
